package:
  name: inkscape
  version: 1.3.2

source:  # [win]
  fn: inkscape-1.3.2.7z
  url: https://inkscape.org/gallery/item/44622/inkscape-1.3.2_2023-11-25_091e20e-x64.7z  # [win64]
  sha256: f1160f5a5f11db6f617c66c6310a726b6c77e28479273b249d8cc8a314b5a059  # [win64]

build:
  skip: true  # [not win]
  number: 0

requirements:
  build:
  - 7za

test:
  commands:
    - inkscape --help

about:
  home: https://inkscape.org
  license: GPL 3
  summary: vector graphics editor (repackaged)

extra:
  recipe-maintainers:
    - janschulz
    - jschueller
    - mcclunatic
