travis:
  secure:
    BINSTAR_TOKEN: SA7MNggrtMUxI7n6jVJXugEljeYUEbNVa1C5xYjbb3jJ19iSJsiEqtzzN7Q34t10lm0wY2d7W9csvPIxy9y8vmh7F0B7xX4MZHTXLncUgVAWNQfITTr4kd+tg9c5FYDybxNb7kj1Dhiu3YZNsbEiMcZOWrbZdI4HWNDyS2MaDEUU3lwephwgk2YAMI2k2TrefvVl+abZ9MEd6gjS0btgwxMQXyd18FTjKE4orvP5Qpe0w35XWnw3d1EB5Ogq+jF2cxug4RXjgGZ9LhBS6haaT9l386iK01u5WTVLM7CB07L45d109pammGf2+M65X6p7ZLHg60AtBkoKbEXo3lSGQoxzYqeCxklsQq2RnpsgnplgieKKqnZsjBjPyH8iXdNv1fVpwdYIDuGHYtXOB7T5ylDGVO1BJoRu08l1kx42++dIyf1nCVhqXu0YGpTYt85EhG1w0QoHSa54GGRzXX3W+wQFAwG6PPPvNGUX+6Rc4QoQtJ4adYdaSbPSPgZkpNONDJkYsezm6wLPRIyV0dxm9WZEA1rs6nSli/VtA4Pa15mM7Ded3CtEb3MPeofTxLRbq+C9INlIrbRPdJRZ9iOoHhJOvumlEWGsQQLshtKyT/HA1sZkRKEhUMrBZTdn1qbUvoudnHN8WCmqLE8VXDhyTRygxoPeby+MM1TuHXZmcmA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
