travis:
  secure:
    BINSTAR_TOKEN: rqgxCjRbGOBO17ltMAuIvOPIRcC/Ie4LGqWiUa70+yQ36grQoIERU6mxl3Z7Ir9ynjkDcZIo5T/TXFj/TQFKcOJgX4PxVHtul9RGUQlHtNEEXnyvkvFAWb7tB8fU9y9l+WwHz8v4gepWgPvHwZeRXUjfXF8C3dbltNo0cAv1c7MhLpeBbNJIRBnYrvjhlHWr3CDzeZVsbvjYFudGNQ2TE/02jY65/DksImoD/5gcr5mtlKFoo8kSSaMhcC5SjVkqZaqFvEv5ZHsqATth5dgY0fcTwtzgNrRnrF8FLGxOEy1FdvDYNWJBiusT+KwD+4UcDcFsUdBpNlRnudo4eDc52YAZH73C1V/61R/aYFDt9adtCOOwrbkZfNC7p+kAiFCWkf7fPN3CyEuSY3XQnuzmHnYybWtez4wXxS6Q7oQrfMuELyiDe2+BDuN1+UZvMJ97Q7tPa8ul196ByTDLUMu55KzPPGrHHXeb99oSuXqfv/dCXdVRC0BdVabDomr3V7PRZKxBufUY6ZnoyRgJ/AET4SSHW4JTL7y036iXQXrke0DMTjO8Hrc5aQP483Ztj3GnKWm00khWV1YNnvplV2yxIQ6Inrj2OF0UlJICNRLBxNCInbwsUnSPLsAZG5ILYMGt/JOssgF6D38C1PbvuAkM2gARlcRlfYXSHI5oV0CSuuo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
