travis:
  secure:
    BINSTAR_TOKEN: EIhLYU6VxNQ8fiShT4iI8F2IB3ixAFSdrcnSX+t7GH6wOU/MNU7ylwllw7ak+7lSQ2vYpjD5vrGfxxE1GseMtQWUH5sNiJmE5vYFobx4jgJyc+x0lAZYmqjfw99c4KNniJxold/mLR232N2L7sVo5hh4cmGyUDUbICKt6PuAbtGrmb6+UlKPt7ZHmMIhMLXYoGIeIRwLbYm+MQdCSWdNeNN66QqSSy/9mPsT1s18ZLux+8FInIJpJi+C2PBDdzAwdHeXp/tSwumHw79saR6Hkkt52nqBrrzcNX9xUk87S61q3RxSWN5KiRO+2PN7JdXfJC8i05ANZ6NqtNOpmv9ooUUOQVw7XWUo+1mY0uvgE5gghHReEi90p1k/PACXCLVkLO4M2NpaHsE6MsSeKgWqGAJtgdMaW2H167xBxGKC9o0iY/Z3wu2X3g6Lv4fxzO9gyT866NHCzuNOO7JZuJnbLL8fb444G9QMI4HI08KiVhmbIqVofKQ2P0Znfp2i6HuqvkNDJt3voyNA4tX/iynPIXARYOK25zUdKOR/uhGIgb0TbkGo8AqY2Fp9HDYjKa4z+4nGc7TBvixFVlUGRE7I8QzKatPM1KyMuzs0wDR5zOernezOQqim8ysw1JlmbxNmPgOc+OpqlzllxlO8BKfHDSrsaX3g6nOjaeRbO4xd5FQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
